on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  publish-to-npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
        pnpm: [6.22.1]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: ${{ matrix.pnpm }}

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        registry-url: https://registry.npmmirror.com/
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Publish to NPM
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        pnpm push
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version

    - name: Create Release for Tag
      id: release_tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: v${{ steps.package-version.outputs.version }}
        prerelease: false
        body: |
          详情请参阅 [CHANGELOG.md](https://github.com/yikoyu/vuetify-pro-layout/blob/v${{ steps.package-version.outputs.version }}/CHANGELOG.md)
